const Products = [
    {
      title:"Trenton modular sofa_3",
      id:1,
      price: 25000,
      img_url:"/Image/chair1.png",
      size:["S, M,L,XL"],
      color:["blue,black,green"],
      qty:1,
      discount:0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },
    {
      title:"Granite dining table with dining chair",
      id:2,
      price:26000,
      img_url:"/Image/chair2.png",
      size:["S, M,L,XL"],
      color:["blue,black,green"],
      discount:0,
      qty:1,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },  {
      title:"Outdoor bar table and stool",
      id:3,
      price: 27000,
      img_url:"/Image/chair3.png",
      size:["S, M,L,XL"],
      discount: 0,
      color:["blue,black,green"],
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png",
      qty:1,
    },  {
      title:"Plain console with teak mirror",
      id:4,
      price:28000,
      img_url:"/Image/chair4.png",
      size:["S, M,L,XL"],
      color:["blue,black,green"],
      qty:1,
      discount: {},
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },
    {
      title:"Grain coffee table",
      id:5,
      price:15000.00,
      img_url:"/Image/desk1.png",
      size:["S, M,L,XL"],
      color:["blue,black,green"],
      qty:1,
      discount: 0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },  {
      title:"Kent coffee table",
      id:6,
      price:225000.00,
      img_url:"/Image/desk2.png",
      size:["S, M,L,XL"],
      color:["blue,black,green"],
      qty:1,
      discount:0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"

    },  {
      title:"Round coffee table_color 2",
      id:7,
      price:251000.00,
      img_url:"/Image/desk3.png",
      size:["S, M,L,XL"],
      color:["blue,black,green"],
      qty:1,
      discount: 0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },  {
      title:"Reclaimed teak coffee table",
      id:8,
      price:25200.00,
      img_url:"/Image/desk4.png",
      size:["S,M,L,XL"],
      color:["blue,black,green"],
      qty:1,
      discount: 0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },
    {
      title:"Plain console_",
      id:9,
      price:258200.00,
      img_url:"/Image/furniture1.png",
      size:["S, M,L,XL"],
      color:["blue,black,green"],
      qty:1,
      discount: 0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },
    {
      title:"Reclaimed teak Sideboard",
      id:10, 
      price:20000.00,
      img_url:"/Image/furniture2.png",
      size:["S, M,L,XL"],
      color:["blue,black,green"],
      qty:1,
      discount: 0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },
    {
      title:"SJP_0825",
      id:11,
      price:200000.00,
      img_url:"/Image/furniture3.png",
      size:["S, M,L,XL"],
      color:["blue,black,green"],
      qty:1,
      discount: 0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },
    {
      title:"Bella chair and table",
      id:12,
      price:100000.00,
      img_url:"/Image/furniture4.png",
      size:["S, M,L,XL"],
      color:["blue,black,green"],
      qty:1,
      discount: 0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png",
    },
    {
      title:"Granite square side table",
      id:13,
      price:258800.00,
      img_url:"/Image/chair5.png",
      size:["S, M,L,XL"],
      color:["#816DFA,#000000,#CDBA7B"],
      qty:1,
      discount:0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },
    {
      title:"Asgaard sofa",
      id:14,
      price:250000.00,
      img_url:"/Image/chair6.png",
      size:["S, M,L,XL"],
      color:["#816DFA,#000000,#CDBA7B"],
      qty:1,
      discount: 0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"

    },
    {
      title:"Maya sofa three seater",
      id:15,
      price:115000.00,
      img_url:"/Image/chair7.png",
      size:["S, M,L,XL"],
      color:["#816DFA,#000000,#CDBA7B"],
      qty:1,
      discount: 0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },
    {
      title:"Outdoor sofa set",
      id:16,
      price:244000.00,
      img_url:"/Image/chair8.png",
      size:["S, M,L,XL"],
      color:["#816DFA,#000000,#CDBA7B"],
      qty:1,
      discount: 0,
      img1:"/Image/sofaset1.png",
      img2:"/Image/sofaset2.png",
      img3:"/Image/sofaset3.png",
      img4:"/Image/sofaset4.png"
    },
  ]

  export default Products;